{% set name = "sklearn2pmml" %}
{% set version = "0.81.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sklearn2pmml-{{ version }}.tar.gz
  sha256: dced9a4f061c14a07e2a82630e240b8d0f1803322085ae16d044351ae5f1aff4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python >=2.7
    - wheel
  run:
    - joblib >=0.13.0
    - python >=2.7
    - scikit-learn >=0.18.0
    - sklearn-pandas >=0.0.10

test:
  imports:
    - sklearn2pmml
    - sklearn2pmml.decoration
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpmml/sklearn2pmml
  summary: Python library for converting Scikit-Learn pipelines to PMML
  license: AGPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  dev_url: https://github.com/jpmml/sklearn2pmml
  doc_url: https://github.com/jpmml/sklearn2pmml/blob/master/README.md
extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/51225
    reason: Client request
    recipe-maintainers:
      - ianaobi
      - bkreider
  recipe-maintainers:
    - FernandezMathieu
