{% set name = "sklearn2pmml" %}
{% set version = "0.73.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sklearn2pmml-{{ version }}.tar.gz
  sha256: 5fbd9719c2e0abbd15f3b018d42e233292ccf7d46c2b844af829c1facdf058cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - joblib >=0.13.0
    - python >=2.7
    - scikit-learn >=0.18.0
    - sklearn-pandas >=0.0.10

test:
  imports:
    - sklearn2pmml
    - sklearn2pmml.decoration
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jpmml/sklearn2pmml
  summary: Python library for converting Scikit-Learn pipelines to PMML
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - FernandezMathieu
